# Copyright (C) 2016 The CyanogenMod Project
# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lge/v20-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev13_S_data1_0x4E.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev13_S_data1_0x4E.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev13_S_data2_0x4E.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev13_S_data2_0x4E.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev14_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev14_S_data1.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev14_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev14_S_data2.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev2_S_data1_0x18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev2_S_data1_0x18.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev2_S_data2_0x18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev2_S_data2_0x18.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev4_S_data1_0x36.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev4_S_data1_0x36.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev4_S_data2_0x36.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_ICG1020S_rev4_S_data2_0x36.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_K2G2IS_rev1_S_data1_0x04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_K2G2IS_rev1_S_data1_0x04.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_LGITAct_K2G2IS_rev1_S_data2_0x04.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_LGITAct_K2G2IS_rev1_S_data2_0x04.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev13_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev13_S_data1.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev13_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev13_S_data2.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev14_S_data1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev14_S_data1.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev14_S_data2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev14_S_data2.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev3.1_S_data1_0x1F.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev3.1_S_data1_0x1F.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev3.1_S_data2_0x1F.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_ICG1020S_rev3.1_S_data2_0x1F.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_K2G2IS_rev1_S_data1_0x03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_K2G2IS_rev1_S_data1_0x03.bin \
    vendor/lge/v20-common/proprietary/vendor/firmware/bu24234_dl_program_Alice_MTMAct_K2G2IS_rev1_S_data2_0x03.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bu24234_dl_program_Alice_MTMAct_K2G2IS_rev1_S_data2_0x03.bin \
    vendor/lge/v20-common/proprietary/vendor/bin/fpc_early_loader:$(TARGET_COPY_OUT_VENDOR)/bin/fpc_early_loader \
    vendor/lge/v20-common/proprietary/vendor/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/lge/v20-common/proprietary/vendor/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/General_cal.acdb \
    vendor/lge/v20-common/proprietary/vendor/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Global_cal.acdb \
    vendor/lge/v20-common/proprietary/vendor/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Handset_cal.acdb \
    vendor/lge/v20-common/proprietary/vendor/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/lge/v20-common/proprietary/vendor/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Headset_cal.acdb \
    vendor/lge/v20-common/proprietary/vendor/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Speaker_cal.acdb \
    vendor/lge/v20-common/proprietary/vendor/lib/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib_fpc_tac_shared.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libactuator_ak7371.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_ak7371.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libactuator_bu24333gwl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu24333gwl.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libactuator_bu24333gwl_s5k2p7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_bu24333gwl_s5k2p7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libarcsoft_beauty_shot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_beauty_shot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libarcsoft_object_tracking.so:$(TARGET_COPY_OUT_VENDOR)/lib/libarcsoft_object_tracking.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libbwfocuspeaking.so:$(TARGET_COPY_OUT_VENDOR)/lib/libbwfocuspeaking.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_csidtg_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_csidtg_common.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_csidtg_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_csidtg_cpp_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_csidtg_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_csidtg_postproc.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_csidtg_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_csidtg_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_csidtg_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_csidtg_zsl_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_3a_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_3a_vt.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_common.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_cpp_liveshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_cpp_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_cpp_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_cpp_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_cpp_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_cpp_vt.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_default_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_default_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_isp_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_isp_vt.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_postproc.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_zsl_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_hi553_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_hi553_zsl_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_4K_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_4K_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_common.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_flash_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_flash_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_hfr_120.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_hfr_60.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_liveshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_liveshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_liveshot_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_panorama.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_raw_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_snapshot_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_cpp_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_default_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_default_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_hdr_video_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_hdr_video_3a.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_hfr_120.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_hfr_120_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_hfr_120_3a.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_hfr_60.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_hfr_60_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_hfr_60_3a.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_panorama_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_panorama_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_postproc.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_raw_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_raw_hdr_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_raw_hdr_3a.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_snapshot_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_snapshot_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_snapshot_hdr_3a.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_snapshot_hdr_3a.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_zsl_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_zsl_preview_wide.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_zsl_preview_wide.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libchromatix_s5k2p7_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k2p7_zsl_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libfilm_emulation.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfilm_emulation.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libflash_pmic.so:$(TARGET_COPY_OUT_VENDOR)/lib/libflash_pmic.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libfpfactory.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfpfactory.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libfpfactory_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib/libfpfactory_jni.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libjpegdhw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdhw.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libjpegdmahw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegdmahw.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libjpegehw.so:$(TARGET_COPY_OUT_VENDOR)/lib/libjpegehw.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_4k_preview_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_4k_preview_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_4k_preview_hi553_cowell.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_4k_preview_hi553_cowell.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_4k_preview_hi553_lgit.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_4k_preview_hi553_lgit.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_4k_video_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_4k_video_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_4k_video_hi553_cowell.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_4k_video_hi553_cowell.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_4k_video_hi553_lgit.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_4k_video_hi553_lgit.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_default_preview_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_default_preview_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_default_preview_hi553_cowell.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_default_preview_hi553_cowell.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_default_preview_hi553_lgit.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_default_preview_hi553_lgit.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_default_video_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_default_video_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_default_video_hi553_cowell.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_default_video_hi553_cowell.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_default_video_hi553_lgit.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_default_video_hi553_lgit.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_hdr_snapshot_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_hdr_snapshot_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_hdr_video_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_hdr_video_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_hfr_120_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_hfr_120_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_hfr_60_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_hfr_60_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_hfr_90_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_hfr_90_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_panorama_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_panorama_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_raw_hdr_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_raw_hdr_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_vt_hi553_cowell.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_vt_hi553_cowell.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_vt_hi553_lgit.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_vt_hi553_lgit.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_zsl_preview_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_zsl_preview_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_zsl_preview_hi553_cowell.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_zsl_preview_hi553_cowell.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_zsl_preview_hi553_lgit.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_zsl_preview_hi553_lgit.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_zsl_video_2P7.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_zsl_video_2P7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_zsl_video_hi553_cowell.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_zsl_video_hi553_cowell.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_ae_parameter_zsl_video_hi553_lgit.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_ae_parameter_zsl_video_hi553_lgit.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_4k_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_4k_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_4k_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_4k_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_default_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_default_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_hdr_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_hdr_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_hdr_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_hdr_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_hfr_120.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_hfr_60.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_hfr_90.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_panorama.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_raw_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_zsl_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_2P7_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_2P7_zsl_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_4k_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_4k_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_4k_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_4k_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_default_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_default_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_hdr_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_hdr_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_hdr_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_hdr_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_hfr_120.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_hfr_60.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_hfr_90.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_panorama.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_raw_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_zsl_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_cowell_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_cowell_zsl_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_4k_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_4k_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_4k_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_4k_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_default_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_default_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_hdr_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_hdr_snapshot.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_hdr_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_hdr_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_hfr_120.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_hfr_60.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_hfr_90.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_panorama.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_raw_hdr.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_raw_hdr.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_zsl_preview.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblg_awb_parameter_hi553_lgit_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblg_awb_parameter_hi553_lgit_zsl_video.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblgae_main.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblgae_main.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblgawb_main.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblgawb_main.so \
    vendor/lge/v20-common/proprietary/vendor/lib/liblghdri.so:$(TARGET_COPY_OUT_VENDOR)/lib/liblghdri.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libmmjpeg_interface.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg_interface.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libmmqjpegdma.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpegdma.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libmorpho_image_stab31.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_image_stab31.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libmorpho_superzoom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmorpho_superzoom.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libmpbase.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmpbase.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libois_bu24333gwl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libois_bu24333gwl.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libois_bu24333gwl_s5k2p7.so:$(TARGET_COPY_OUT_VENDOR)/lib/libois_bu24333gwl_s5k2p7.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libois_lc898122.so:$(TARGET_COPY_OUT_VENDOR)/lib/libois_lc898122.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libqomx_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_core.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libqomx_jpegdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegdec.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so \
    vendor/lge/v20-common/proprietary/vendor/lib/libqomx_jpegenc_pipe.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc_pipe.so \
    vendor/lge/v20-common/proprietary/vendor/lib64/lib_fpc_tac_shared.so:$(TARGET_COPY_OUT_VENDOR)/lib64/lib_fpc_tac_shared.so \
    vendor/lge/v20-common/proprietary/vendor/lib64/libfpfactory.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfpfactory.so \
    vendor/lge/v20-common/proprietary/vendor/lib64/libfpfactory_jni.so:$(TARGET_COPY_OUT_VENDOR)/lib64/libfpfactory_jni.so \

PRODUCT_PACKAGES += \
    fingerprint.msm8996
